### ISSUE TITLE
Packets to be parsed checklist

### ISSUE THREAD

**Issue by rubellyte** [medeor413/Project-Apophis#1]
### Packets parsed:
Connection protocol handshake:
- [x] PROTOCOL_REQUEST
- [x] PROTOCOL_RESPONSE
Universe; server -> client:
- [x] SERVER_DISCONNECT
- [x] CONNECT_SUCCESS
- [x] CONNECT_FAILURE
- [x] HANDSHAKE_CHALLENGE
- [x] CHAT_RECEIVED
- [x] UNIVERSE_TIME_UPDATE
- [ ] CELESTIAL_RESPONSE
- [x] PLAYER_WARP_RESULT
- [ ] PLANET_TYPE_UPDATE
- [ ] PAUSE
- [ ] SERVER_INFO
Universe; client -> server:
- [x] CLIENT_CONNECT
- [ ] CLIENT_DISCONNECT_REQUEST
- [x] HANDSHAKE_RESPONSE
- [x] PLAYER_WARP
- [x] FLY_SHIP
- [x] CHAT_SENT
- [ ] CELESTIAL_REQUEST
Universe; client <--> server:
- [x] CLIENT_CONTEXT_UPDATE (currently server -> client only)
World; server -> client:
- [x] WORLD_START
- [x] WORLD_STOP
- [ ] WORLD_LAYOUT_UPDATE
- [ ] WORLD_PARAMETERS_UPDATE
- [ ] CENTRAL_STRUCTURE_UPDATE
- [ ] TILE_ARRAY_UPDATE
- [ ] TILE_UPDATE
- [ ] TILE_LIQUID_UPDATE
- [ ] TILE_DAMAGE_UPDATE
- [ ] TILE_MODIFICATION_FAILURE
- [x] GIVE_ITEM
- [ ] ENVIRONMENT_UPDATE
- [ ] UPDATE_TILE_PROTECTION
- [ ] SET_DUNGEON_GRAVITY
- [ ] SET_DUNGEON_BREATHABLE
- [ ] SET_PLAYER_START
- [ ] FIND_UNIQUE_ENTITY_RESPONSE
- [ ] PONG
World; client -> server:
- [ ] MODIFY_TILE_LIST
- [ ] DAMAGE_TILE_GROUP
- [ ] COLLECT_LIQUID
- [ ] REQUEST_DROP
- [x] SPAWN_ENTITY
- [ ] CONNECT_WIRE
- [ ] DISCONNECT_ALL_WIRES
- [ ] WORLD_CLIENT_STATE_UPDATE
- [ ] FIND_UNIQUE_ENTITY
- [ ] WORLD_START_ACKNOWLEDGE
- [ ] PING
World; client <--> server:
- [x] ENTITY_CREATE
- [x] ENTITY_UPDATE
- [ ] ENTITY_DESTROY
- [x] ENTITY_INTERACT
- [x] ENTITY_INTERACT_RESULT
- [ ] HIT_REQUEST
- [x] DAMAGE_REQUEST
- [x] DAMAGE_NOTIFICATION
- [x] ENTITY_MESSAGE
- [x] ENTITY_MESSAGE_RESPONSE
- [ ] UPDATE_WORLD_PROPERTIES
- [x] STEP_UPDATE
System; server -> client:
- [ ] SYSTEM_WORLD_START
- [ ] SYSTEM_WORLD_UPDATE
- [ ] SYSTEM_OBJECT_CREATE
- [ ] SYSTEM_OBJECT_DESTROY
- [ ] SYSTEM_SHIP_CREATE
- [ ] SYSTEM_SHIP_DESTROY
System; client -> server:
- [ ] SYSTEM_OBJECT_SPAWN
